# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 142640e2eb1bb0ac0dfdd09602d550aa507d9dcb907a60ae8b2b4a8f99c522e11e42000f091dbf5676846c6e951180f5695dbd4119774a37513ab3f8885dea34

test:
  secret_key_base: 7f9a2772ab4098d7da1929b65c1dd5b26a19408267b8ca87b6259942c7a0332ecc0a4e33cbf5efcc4461ed82edd75192ac5ebe8eb3c6650dcef76e2f6c5b386a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
